# services:
#   web:
#     image: nginx:alpine
#     ports:
#       - "8080:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - app

#   app:
#     image: openjdk:11
#     volumes:
#       - ./app:/var/www/html
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/demo
#       SPRING_DATASOURCE_USERNAME: root
#       SPRING_DATASOURCE_PASSWORD: demo
#     depends_on:
#       - db

# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/db_name
#     username: root
#     password: password
#   jpa:
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQLDialect
  
#   db:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: demo
#       MYSQL_USER: root
#       MYSQL_PASSWORD: demo
#     ports:
#       - "3306:3306"